# For running in local development: hot reload etc
services:
  frontend-dev:
    container_name: nowdb-frontend-dev
    build:
      context: ./frontend
      dockerfile: ./dev.Dockerfile
    volumes:
      - ./frontend/src:/usr/src/app/src
    ports:
      - 127.0.0.1:5173:5173
    env_file: .dev.env

  backend-dev:
    container_name: nowdb-backend-dev
    build:
      context: .
      dockerfile: ./backend/dev.Dockerfile
    volumes:
      - ./backend/src:/usr/src/app/backend/src
      - ./frontend/src/:/usr/src/app/frontend/src/
    ports:
      - 127.0.0.1:4000:4000
    env_file: .dev.env

  db:
    container_name: nowdb-db-dev
    image: mariadb:11.4.3
    env_file: .dev.env
    volumes:
      - ./data/:/docker-entrypoint-initdb.d
      - nowdb-db:/var/lib/mysql/data
    ports:
      - 127.0.0.1:3306:3306

volumes:
  nowdb-db:

