# For running in local development: hot reload etc
services:
  frontend:
    container_name: nowdb-frontend-dev
    image: node:20-alpine3.16
    volumes:
      - ./frontend/:/usr/src/app
    ports:
      - 127.0.0.1:5173:5173
    command: >
        sh -c "cd /usr/src/app && npm ci && npm run dev -- --host"
  backend:
    container_name: nowdb-backend-dev
    image: node:20-alpine3.16
    volumes:
      - ./backend/:/usr/src/app
    ports:
      - 127.0.0.1:4000:4000
    command: >
        sh -c "cd /usr/src/app && npm ci && npm run dev"
    env_file: .db.dev.env
  db:
    container_name: nowdb-db-dev
    image: mariadb
    env_file: .db.dev.env
    volumes:
      - ./data/:/docker-entrypoint-initdb.d
      - nowdb-db:/var/lib/mysql/data
    ports:
      - 127.0.0.1:3306:3306
volumes:
  nowdb-db:

