# For running tests with anonymous data, github actions utilize this
services:
  frontend:
    container_name: nowdb-frontend-anon
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - 127.0.0.1:5173:5173
    env_file: .anon.env
  backend:
    container_name: nowdb-backend-anon
    depends_on:
      db-anon:
        condition: service_healthy
    env_file: .anon.env
    ports:
      - 127.0.0.1:4000:4000
    build:
      context: .
      dockerfile: ./backend/Dockerfile
      target: node-run
    healthcheck:
      test: curl -f http://localhost:4000/test/ping || exit 1
      start_period: 10s
      interval: 30s
      retries: 3
      timeout: 15s

  api-tests:
    container_name: nowdb-api-tests-anon
    depends_on:
      db-anon:
        condition: service_healthy
      backend:
        condition: service_healthy
    build:
      context: .
      dockerfile: ./backend/Dockerfile
      target: api-tests

  db-anon:
    container_name: nowdb-db-anon
    image: mariadb:11.4.3
    env_file: .anon.env
    volumes:
      - ./test_data/:/docker-entrypoint-initdb.d
    ports:
      - 127.0.0.1:3306:3306
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      start_period: 10s
      interval: 10s
      timeout: 5s
      retries: 3
