# Static builds, but for running locally
services:
  frontend:
    container_name: nowdb-frontend
    env_file: .env
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        BACKEND_URL: http://localhost:4000
        ENABLE_WRITE: true
        RUNNING_ENV: prod
        GEONAMES_USERNAME: '${GEONAMES_USERNAME}'
    ports:
      - 127.0.0.1:5173:5173

  backend:
    container_name: nowdb-backend
    env_file: .env
    build:
      context: .
      dockerfile: ./backend/Dockerfile
      target: node-run
    ports:
      - 127.0.0.1:4000:4000

  db:
    container_name: nowdb-db
    image: mariadb:11.4.3
    env_file: .env
    volumes:
      - ./data/:/docker-entrypoint-initdb.d
      - nowdb-db:/var/lib/mysql/data

volumes:
  nowdb-db:
