services:
  now-db-frontend:
    container_name: nowdb-frontend
    image: node:20
    volumes:
      - ./frontend/:/usr/src/app
    ports:
      - 5173:5173
    command: >
        sh -c "cd /usr/src/app && npm ci && npm run dev -- --host"