# Static builds, but for running locally
services:
  frontend:
    container_name: nowdb-frontend
    build:
      context: frontend/
    volumes:
      - ./frontend/:/usr/src/app
    ports:
      - 5173:5173
    environment:
      - BACKEND_URL=http://localhost:4000
  backend:
    container_name: nowdb-backend
    build:
      context: backend/
    env_file: .env
    ports:
      - 4000:4000
  db:
    container_name: nowdb-db
    image: mariadb
    env_file: .env
    volumes:
      - ./data/:/docker-entrypoint-initdb.d
      - nowdb-db:/var/lib/mysql/data
volumes:
  nowdb-db:
