import { describe, expect, it } from '@jest/globals'
import JSZip from 'jszip'
import {
  buildDwcOccurrenceArchiveZipBufferFromOccurrences,
  mapOccurrenceToMeasurementRows,
  mapOccurrenceToOccurrenceRow,
} from '../services/dwcArchiveExportOccurrences'

describe('DwC-A occurrence export mapping', () => {
  const baseOccurrence = {
    lid: 42,
    species_id: 21052,
    nis: 7,
    pct: null,
    quad: null,
    mni: 2,
    qua: 'A',
    id_status: 'confirmed',
    orig_entry: 'Original occurrence note',
    source_name: 'Source collection',
    body_mass: BigInt(1234),
    mesowear: 'mix',
    mw_or_high: 1,
    mw_or_low: null,
    mw_cs_sharp: null,
    mw_cs_round: 2,
    mw_cs_blunt: null,
    mw_scale_min: 0,
    mw_scale_max: 3,
    mw_value: 2,
    microwear: 'scratch',
    dc13_mean: -11.2,
    dc13_n: 4,
    dc13_max: -10.1,
    dc13_min: -12.3,
    dc13_stdev: 0.4,
    do18_mean: 1.2,
    do18_n: 3,
    do18_max: 2.4,
    do18_min: 0.4,
    do18_stdev: 0.5,
    now_loc: {
      lid: 42,
      loc_name: 'Test locality',
      basin: 'Test basin',
      subbasin: 'Test subbasin',
      country: 'Finland',
      state: 'Uusimaa',
      county: 'Helsinki',
      dec_lat: 60.1699,
      dec_long: 24.9384,
      dms_lat: null,
      dms_long: null,
      approx_coord: null,
      altitude: 123,
      loc_detail: 'Some notes',
      chron: 'Test chron',
      lgroup: 'Test group',
      formation: 'Test formation',
      member: 'Test member',
      bed: 'Test bed',
      bfa_max: 'BFA_MAX',
      bfa_min: 'BFA_MIN',
      bfa_max_abs: null,
      bfa_min_abs: null,
      frac_max: null,
      frac_min: null,
      max_age: 12.3,
      min_age: 4.5,
      date_meth: 'radioisotope',
      age_comm: 'Age comment',
      site_area: null,
      gen_loc: null,
      plate: null,
      appr_num_spm: null,
      num_spm: null,
      true_quant: null,
      complete: null,
      num_quad: null,
      rock_type: null,
      rt_adj: null,
      lith_comm: null,
      depo_context1: null,
      depo_context2: null,
      depo_context3: null,
      depo_context4: null,
      depo_comm: null,
      sed_env_1: null,
      sed_env_2: null,
      event_circum: null,
      se_comm: null,
      assem_fm: null,
      transport: null,
      trans_mod: null,
      weath_trmp: null,
      pt_conc: null,
      size_type: null,
      vert_pres: null,
      plant_pres: null,
      invert_pres: null,
      time_rep: null,
      taph_comm: null,
      tax_comm: null,
      datum_plane: null,
      tos: null,
      bos: null,
      loc_status: null,
      hominin_skeletal_remains: false,
      climate_type: null,
      biome: null,
      v_ht: null,
      v_struct: null,
      v_envi_det: null,
      disturb: null,
      nutrients: null,
      water: null,
      seasonality: null,
      seas_intens: null,
      pri_prod: null,
      moisture: null,
      temperature: null,
      estimate_precip: null,
      estimate_temp: null,
      estimate_npp: null,
      pers_woody_cover: null,
      pers_pollen_ap: null,
      pers_pollen_nap: null,
      pers_pollen_other: null,
      stone_tool_cut_marks_on_bones: false,
      bipedal_footprints: false,
      stone_tool_technology: false,
      technological_mode_1: null,
      technological_mode_2: null,
      technological_mode_3: null,
      cultural_stage_1: null,
      cultural_stage_2: null,
      cultural_stage_3: null,
      regional_culture_1: null,
      regional_culture_2: null,
      regional_culture_3: null,
      now_syn_loc: [],
      now_ss: [],
      now_coll_meth: [],
      now_mus: [],
      now_ls: [],
      now_time_unit_now_loc_bfa_maxTonow_time_unit: null,
      now_time_unit_now_loc_bfa_minTonow_time_unit: null,
    },
    com_species: {
      species_id: 21052,
      class_name: 'Mammalia',
      subclass_or_superorder_name: null,
      order_name: 'Rodentia',
      suborder_or_superfamily_name: null,
      family_name: 'Testidae',
      subfamily_name: null,
      genus_name: 'Simplomys',
      species_name: 'simplicidens',
      unique_identifier: '-',
      taxonomic_status: null,
      common_name: null,
      sp_author: 'Test Author',
      sp_comment: null,
    },
  } as const

  it('maps now_ls row to a DwC Occurrence row', () => {
    const row = mapOccurrenceToOccurrenceRow(baseOccurrence)
    expect(row).toEqual(
      expect.objectContaining({
        occurrenceID: 'NOW:OCC:42:21052',
        locationID: 'NOW:LOC:42',
        taxonID: 'NOW:21052',
        scientificName: 'Simplomys simplicidens Test Author',
        occurrenceStatus: 'present',
        organismQuantity: '2',
        organismQuantityType: 'minimum number of individuals',
        identificationQualifier: 'confirmed',
        occurrenceRemarks: 'Original occurrence note | Source collection | A',
      })
    )
  })

  it('prefixes now_ls measurement verbatim names to avoid com_species collisions', () => {
    const rows = mapOccurrenceToMeasurementRows(baseOccurrence)
    expect(rows).toEqual(
      expect.arrayContaining([
        expect.objectContaining({
          taxonID: 'NOW:OCC:42:21052',
          measurementID: 'NOW:OCC:42:21052:now_ls.body_mass',
          verbatimMeasurementType: 'now_ls.body_mass',
          measurementValue: '1234',
          measurementUnit: 'g',
        }),
        expect.objectContaining({
          measurementID: 'NOW:OCC:42:21052:now_ls.mesowear',
          verbatimMeasurementType: 'now_ls.mesowear',
          measurementValue: 'mix',
        }),
      ])
    )
  })

  it('generates a ZIP archive with occurrence export files', async () => {
    const zipBuffer = await buildDwcOccurrenceArchiveZipBufferFromOccurrences([baseOccurrence])
    const zip = await JSZip.loadAsync(zipBuffer)
    expect(zip.file('location.csv')).toBeTruthy()
    expect(zip.file('geologicalcontext.csv')).toBeTruthy()
    expect(zip.file('taxon.csv')).toBeTruthy()
    expect(zip.file('occurrence.csv')).toBeTruthy()
    expect(zip.file('measurementorfact.csv')).toBeTruthy()
    expect(zip.file('meta.xml')).toBeTruthy()
    expect(zip.file('eml.xml')).toBeTruthy()
  })
})
