import { describe, it, expect } from '@jest/globals'
import { localitiesToKML } from '../utils/klm'
import { Locality } from '../../../frontend/src/shared/types'

const testLocalities: Locality[] = [
  {
    lid: 20920,
    loc_name: 'Lantian-Shuijiazui',
    bfa_max: 'bahean',
    bfa_min: 'bahean',
    max_age: 11.63,
    min_age: 7.2,
    bfa_max_abs: null,
    bfa_min_abs: null,
    frac_max: null,
    frac_min: null,
    chron: '',
    age_comm: '',
    basin: 'Fenwei',
    subbasin: 'Weihe',
    dms_lat: '34 6 0 N',
    dms_long: '109 18 0 E',
    dec_lat: 34.1,
    dec_long: 109.3,
    altitude: 0,
    country: 'China',
    state: 'Shaanxi',
    county: 'Lantian',
    appr_num_spm: 0,
    site_area: '100-1000m2',
    gen_loc: 'y',
    plate: '',
    formation: 'Bahe',
    member: '',
    bed: '',
    loc_status: false,
    estimate_precip: null,
    estimate_temp: null,
    estimate_npp: null,
    pers_woody_cover: null,
    pers_pollen_ap: null,
    pers_pollen_nap: null,
    pers_pollen_other: null,
    hominin_skeletal_remains: false,
    bipedal_footprints: false,
    stone_tool_cut_marks_on_bones: false,
    stone_tool_technology: false,
    technological_mode_1: null,
    technological_mode_2: null,
    technological_mode_3: null,
    cultural_stage_1: null,
    cultural_stage_2: null,
    cultural_stage_3: null,
    regional_culture_1: null,
    regional_culture_2: null,
    regional_culture_3: null,
  },
  {
    lid: 21050,
    loc_name: 'Dmanisi',
    bfa_max: null,
    bfa_min: 'olduvai',
    max_age: 1.85,
    min_age: 1.778,
    bfa_max_abs: 'Ar/Ar',
    bfa_min_abs: null,
    frac_max: null,
    frac_min: null,
    chron: 'Villafranchian, MNQ18',
    age_comm: 'before Acheulian: E. hydruntinus, stone tools.1.81 Ma based on volcanic ash dating',
    basin: null,
    subbasin: null,
    dms_lat: '41 20 10 N',
    dms_long: '44 20 38 E',
    dec_lat: 41.33611111111112,
    dec_long: 44.34388888888889,
    altitude: 0,
    country: 'Georgia',
    state: 'Tbilisi area',
    county: '',
    appr_num_spm: 0,
    site_area: '',
    gen_loc: 'n',
    plate: '',
    formation: '',
    member: '',
    bed: '',
    loc_status: false,
    estimate_precip: null,
    estimate_temp: null,
    estimate_npp: null,
    pers_woody_cover: null,
    pers_pollen_ap: null,
    pers_pollen_nap: null,
    pers_pollen_other: null,
    hominin_skeletal_remains: false,
    bipedal_footprints: false,
    stone_tool_cut_marks_on_bones: false,
    stone_tool_technology: false,
    technological_mode_1: null,
    technological_mode_2: null,
    technological_mode_3: null,
    cultural_stage_1: null,
    cultural_stage_2: null,
    cultural_stage_3: null,
    regional_culture_1: null,
    regional_culture_2: null,
    regional_culture_3: null,
  },
  {
    lid: 24750,
    loc_name: 'RomanyÃ  dEmpordÃ ',
    bfa_max: null,
    bfa_min: null,
    max_age: 7.1,
    min_age: 5.3,
    bfa_max_abs: 'Ar/Ar',
    bfa_min_abs: 'AAR',
    frac_max: null,
    frac_min: null,
    chron: 'Turolian',
    age_comm: null,
    basin: 'Ebro',
    subbasin: null,
    dms_lat: '42 9 58 N',
    dms_long: '2 39 58 E',
    dec_lat: 42.166,
    dec_long: 2.666,
    altitude: 0,
    country: 'Spain',
    state: 'Province of Girona',
    county: null,
    appr_num_spm: 0,
    site_area: null,
    gen_loc: null,
    plate: null,
    formation: null,
    member: null,
    bed: null,
    loc_status: false,
    estimate_precip: null,
    estimate_temp: null,
    estimate_npp: null,
    pers_woody_cover: null,
    pers_pollen_ap: null,
    pers_pollen_nap: null,
    pers_pollen_other: null,
    hominin_skeletal_remains: false,
    bipedal_footprints: false,
    stone_tool_cut_marks_on_bones: false,
    stone_tool_technology: false,
    technological_mode_1: null,
    technological_mode_2: null,
    technological_mode_3: null,
    cultural_stage_1: null,
    cultural_stage_2: null,
    cultural_stage_3: null,
    regional_culture_1: null,
    regional_culture_2: null,
    regional_culture_3: null,
  },
  {
    lid: 24797,
    loc_name: 'Las Umbrias 1',
    bfa_max: 'mn5',
    bfa_min: 'mn5',
    max_age: 16.4,
    min_age: 14.2,
    bfa_max_abs: null,
    bfa_min_abs: null,
    frac_max: null,
    frac_min: null,
    chron: 'Aragonian, zone Dd',
    age_comm: 'C5Adn',
    basin: 'Iberian Range',
    subbasin: null,
    dms_lat: '41 11 46 N',
    dms_long: '1 30 38 W',
    dec_lat: 41.1963254,
    dec_long: -1.5106093,
    altitude: 0,
    country: 'Spain',
    state: 'Province of Zaragoza',
    county: null,
    appr_num_spm: 0,
    site_area: null,
    gen_loc: null,
    plate: null,
    formation: null,
    member: null,
    bed: null,
    loc_status: false,
    estimate_precip: null,
    estimate_temp: null,
    estimate_npp: null,
    pers_woody_cover: null,
    pers_pollen_ap: null,
    pers_pollen_nap: null,
    pers_pollen_other: null,
    hominin_skeletal_remains: false,
    bipedal_footprints: false,
    stone_tool_cut_marks_on_bones: false,
    stone_tool_technology: false,
    technological_mode_1: null,
    technological_mode_2: null,
    technological_mode_3: null,
    cultural_stage_1: null,
    cultural_stage_2: null,
    cultural_stage_3: null,
    regional_culture_1: null,
    regional_culture_2: null,
    regional_culture_3: null,
  },
  {
    lid: 28518,
    loc_name: 'Goishi',
    bfa_max: 'langhian',
    bfa_min: 'langhian',
    max_age: 15.97,
    min_age: 13.82,
    bfa_max_abs: null,
    bfa_min_abs: null,
    frac_max: null,
    frac_min: null,
    chron: null,
    age_comm: null,
    basin: 'Joban',
    subbasin: null,
    dms_lat: '38 12 0 N',
    dms_long: '140 42 0 E',
    dec_lat: 38.2,
    dec_long: 140.7,
    altitude: 0,
    country: 'Japan',
    state: 'Miyagi Prefecture',
    county: null,
    appr_num_spm: 0,
    site_area: null,
    gen_loc: null,
    plate: null,
    formation: 'Moniwa',
    member: null,
    bed: null,
    loc_status: false,
    estimate_precip: null,
    estimate_temp: null,
    estimate_npp: null,
    pers_woody_cover: null,
    pers_pollen_ap: null,
    pers_pollen_nap: null,
    pers_pollen_other: null,
    hominin_skeletal_remains: false,
    bipedal_footprints: false,
    stone_tool_cut_marks_on_bones: false,
    stone_tool_technology: false,
    technological_mode_1: null,
    technological_mode_2: null,
    technological_mode_3: null,
    cultural_stage_1: null,
    cultural_stage_2: null,
    cultural_stage_3: null,
    regional_culture_1: null,
    regional_culture_2: null,
    regional_culture_3: null,
  },
  {
    lid: 29999,
    loc_name: 'not in cross search',
    bfa_max: null,
    bfa_min: null,
    max_age: 15.97,
    min_age: 13.82,
    bfa_max_abs: null,
    bfa_min_abs: null,
    frac_max: null,
    frac_min: null,
    chron: null,
    age_comm: null,
    basin: 'Joban',
    subbasin: null,
    dms_lat: '38 12 0 N',
    dms_long: '140 42 0 E',
    dec_lat: 38.2,
    dec_long: 140.7,
    altitude: 0,
    country: 'Japan',
    state: 'Miyagi Prefecture',
    county: null,
    appr_num_spm: 0,
    site_area: null,
    gen_loc: null,
    plate: null,
    formation: 'Moniwa',
    member: null,
    bed: null,
    loc_status: false,
    estimate_precip: null,
    estimate_temp: null,
    estimate_npp: null,
    pers_woody_cover: null,
    pers_pollen_ap: null,
    pers_pollen_nap: null,
    pers_pollen_other: null,
    hominin_skeletal_remains: false,
    bipedal_footprints: false,
    stone_tool_cut_marks_on_bones: false,
    stone_tool_technology: false,
    technological_mode_1: null,
    technological_mode_2: null,
    technological_mode_3: null,
    cultural_stage_1: null,
    cultural_stage_2: null,
    cultural_stage_3: null,
    regional_culture_1: null,
    regional_culture_2: null,
    regional_culture_3: null,
  },
]

const testKlm = `<?xml version="1.0" encoding="UTF-8"?><kml xmlns="http://www.opengis.net/kml/2.2"><Document><name>Luomus locality data</name><Folder><name>Luomus localities</name><Placemark><name>Lantian-Shuijiazui</name><description></description><Point><coordinates>109.3,34.1,0</coordinates></Point></Placemark>,<Placemark><name>Dmanisi</name><description></description><Point><coordinates>44.34388888888889,41.33611111111112,0</coordinates></Point></Placemark>,<Placemark><name>RomanyÃ  dEmpordÃ </name><description></description><Point><coordinates>2.666,42.166,0</coordinates></Point></Placemark>,<Placemark><name>Las Umbrias 1</name><description></description><Point><coordinates>-1.5106093,41.1963254,0</coordinates></Point></Placemark>,<Placemark><name>Goishi</name><description></description><Point><coordinates>140.7,38.2,0</coordinates></Point></Placemark>,<Placemark><name>not in cross search</name><description></description><Point><coordinates>140.7,38.2,0</coordinates></Point></Placemark></Folder></Document></kml>`

describe('KML generation', () => {
  it('Returns expected KML', () => {
    expect(localitiesToKML(testLocalities)).toEqual(testKlm)
  })
})
