import { SpeciesDetailsType } from '../../../frontend/src/backendTypes'

export const newLocalityBasis = {
  bfa_max: 'bahean',
  bfa_min: 'bahean',
  loc_name: 'Lantian-Shuijiazui',
  date_meth: 'time_unit',
  max_age: 11.63,
  min_age: 7.2,
  bfa_max_abs: null,
  bfa_min_abs: null,
  frac_max: null,
  frac_min: null,
  chron: '',
  age_comm: '',
  basin: 'Fenwei',
  subbasin: 'Weihe',
  dms_lat: '34 6 0 N',
  dms_long: '109 18 0 E',
  dec_lat: 34.1,
  dec_long: 109.3,
  approx_coord: null,
  altitude: null,
  country: 'China',
  state: 'Shaanxi',
  county: 'Lantian',
  site_area: '100-1000m2',
  gen_loc: 'y',
  plate: '',
  loc_detail: '',
  lgroup: '',
  formation: 'Bahe',
  member: '',
  bed: '',
  datum_plane: '',
  tos: null,
  bos: null,
  rock_type: 'sandstone',
  rt_adj: '',
  lith_comm: '',
  depo_context1: null,
  depo_context2: null,
  depo_context3: null,
  depo_context4: null,
  depo_comm: null,
  sed_env_1: '',
  sed_env_2: '',
  event_circum: '',
  se_comm: '',
  climate_type: '',
  biome: '',
  v_ht: '',
  v_struct: '',
  v_envi_det: '',
  disturb: '',
  nutrients: '',
  water: '',
  seasonality: '',
  seas_intens: '',
  pri_prod: '',
  moisture: '',
  temperature: '',
  assem_fm: '',
  transport: '',
  trans_mod: '',
  weath_trmp: '',
  pt_conc: '',
  size_type: '',
  vert_pres: '',
  plant_pres: '',
  invert_pres: '',
  time_rep: '',
  appr_num_spm: null,
  num_spm: null,
  true_quant: '',
  complete: 'y',
  num_quad: null,
  taph_comm: '',
  tax_comm: null,
  loc_status: false,
  estimate_precip: null,
  estimate_temp: null,
  estimate_npp: null,
  pers_woody_cover: null,
  pers_pollen_ap: null,
  pers_pollen_nap: null,
  pers_pollen_other: null,
  hominin_skeletal_remains: false,
  bipedal_footprints: false,
  stone_tool_technology: false,
  stone_tool_cut_marks_on_bones: false,
  technological_mode_1: null,
  technological_mode_2: null,
  technological_mode_3: null,
  cultural_stage_1: null,
  cultural_stage_2: null,
  cultural_stage_3: null,
  regional_culture_1: null,
  regional_culture_2: null,
  regional_culture_3: null,
  now_mus: [
    {
      lid: 20920,
      museum: 'RGM',
      com_mlist: {
        museum: 'RGM',
        institution: 'Naturalis: National Museum of Natural History',
        alt_int_name: 'Nationaal Natuurhistorisch Museum, former Rijksmuseum van Geologie en Mineralogie',
        city: 'Leiden',
        state_code: '',
        state: '',
        country: 'Netherlands',
        used_morph: null,
        used_now: true,
        used_gene: null,
      },
    },
  ],
  now_ls: [
    {
      rowState: 'new',
      com_species: { species_name: 'Newspecies' } as SpeciesDetailsType,
    },
    {
      rowState: 'new',
      species_id: 21052,
      com_species: { species_id: 21052 } as SpeciesDetailsType,
    },
  ],
  now_syn_loc: [
    {
      syn_id: 2373,
      lid: 20920,
      synonym: 'Shuijiazui',
    },
    {
      syn_id: 6066,
      lid: 20920,
      synonym: 'Bahe',
    },
  ],
  now_ss: [
    {
      lid: 20920,
      sed_struct: 'crocodile_frags',
    },
    {
      lid: 20920,
      sed_struct: 'm_cones',
    },
    {
      lid: 20920,
      sed_struct: 'tool_marks',
    },
  ],
  now_coll_meth: [
    {
      lid: 20920,
      coll_meth: 'surface',
    },
    {
      lid: 20920,
      coll_meth: 'systematic_loc_survey',
    },
  ],
  now_plr: [
    {
      lid: 20920,
      pid: 3,
      now_proj: {
        pid: 3,
        contact: 'AD',
        proj_code: 'NOW',
        proj_name: 'NOW Database',
        proj_status: 'current',
        proj_records: false,
      },
    },
  ],
}
