name: 'End-to-end tests'

on:
  pull_request:
<<<<<<< Updated upstream
    types: [opened, reopened]
=======
    types: [opened, reopened, synchronize]
  push:
>>>>>>> Stashed changes
    branches:
      - '**'
    paths-ignore:
      - '**/*.md'
      - '.github/workflows/build.yaml'

jobs:
  e2e_tests:
    name: 'End-to-end tests'
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: 'Run setup'
        run: npm run setup

      - name: 'Start containers'
        run: npm run start:anon -- -d && sleep 60
      - name: Cypress
        uses: cypress-io/github-action@v6
      - name: Dump docker logs on failure
        if: failure()
        uses: jwalton/gh-docker-logs@v2
