name: 'End-to-end tests'

on:
  pull_request:
    types: [opened, reopened, synchronize]
    branches:
      - '**'
    paths-ignore:
      - '.github/workflows/build.yaml'

jobs:
  e2e_tests:
    name: 'End-to-end tests'
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: Run e2e tests
        run: npm run test:docker:ci:e2e

      - name: Dump docker logs on failure
        if: failure()
        uses: jwalton/gh-docker-logs@v2
